export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = '';
export const developedBy = 'Techzaa';
export const contactUs = 'techzaastudio@gmail.com';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'Maypas Estate';
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'purple', 'pink', 'orange', 'light', 'link'];